#!/bin/bash

gfile=$1; shift

[ -z "$gfile" ] && {
    >&2 echo "error: please, specify file for G"
    exit 1
}

[ -f "$gfile" ] || {
    >&2 echo "error: please, make sure file specified for G is valid"
    exit 1
}

! [ -d "./small_graphs" ] && ./generate_small_graphs.py

for gsize in {2..7}; do
    to_break=0
    for hfile in $(find small_graphs -name "graph_${gsize}*" | sort -V); do
        echo "trying $hfile"
        info=$(./gap_homomorphism_finder "$gfile" "$hfile")
        # echo "$info"
        [ -z "$(echo "$info" | grep -v fail)" ] && {
            continue
        }
        info=$(./gap_homomorphism_finder "$hfile" "$gfile")
        # echo "$info"
        [ -z "$(echo "$info" | grep -v fail)" ] || {
            to_break=1
            echo "found core of $gfile: $hfile"
            break
        }
    done
    [ $to_break -eq 1 ] && break
done
