#!/bin/bash

maxthreads=4
nothreads=0

find frames -name 'frame_lattice_*.json' | sort -R | while IFS= read -r line; do
    lframe="$line"
    pngname="${lframe/.json/.png}"
    framename="${pngname/lattice_/}"
    ! [ -e "${framename}" ] && {
        [ $nothreads -eq $maxthreads ] && {
            wait
            nothreads=0
        }
        echo "frame ${framename}"
        touch "${framename}"
        ./make_lattice_frame.py "${lframe}" &
        ((++nothreads))
    }
done
wait
