#!/bin/bash

for gfile in graphs/*; do
    for hfile in small_graphs/*; do
        gap_res=$(./gap_is_homomorphic_gh "$gfile" "$hfile")
        sh_res=$(./solve_homomorphism.py "$gfile" "$hfile" | tail -1)
        [ "$sh_res" = fail ] && sh_res=NO || sh_res=YES
        echo "$gfile $hfile $gap_res $sh_res"
        [ "$gap_res" != "$sh_res" ] && {
            echo "test failed"
            exit 1
        }
    done
done
