#!/bin/bash

[ -e movie.mp4 ] && rm -vf movie.mp4
ffmpeg -r 5 -f image2 -s 1600x1600 -i frame_%d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p test.mp4
ffmpeg -i test.mp4 -i Eric*.mp3 -filter_complex " [1:0] apad " -shortest movie.mp4
rm -vf test.mp4
